### ISSUE TITLE
New default step - random password generation

### ISSUE THREAD

**Issue by sergeytrasko** [ctco/cukes#102]
Often it is needed to generate a random password matching some policy. E.g. one upper-case letter, one lower-case letter, one digit, etc.

It would be good to have a default step so one can do something like this:
```
let variable "password" equal to random password matching pattern "AaaaA111"
```

Where "A" will be replaced with random upper-case letter, "a" - with lower-case letter and "1" with random digit.

Any other options for patterns are possible and welcomed

**Comment by mike-hmelov** [comment]
Number pattern symbol will be 0 instead of 1
So: Where "A" will be replaced with random upper-case letter, "a" - with lower-case letter and "0" with random digit.
