### ISSUE TITLE
Help on running cukes-rest-sample

### ISSUE THREAD

**Issue by arkadiyala** [ctco/cukes#87]
I see below from README.md
There are two options to start local server with Sample Application:
- Run SampleApplicaiton.java with following params server server.yml from $MODULE_DIR$
- Execute Package/Install Maven phase of the parent project cukes-rest-all

I have stored this framework at C:\workspace\Rest\cukes-rest-sample. Could you please help me on how to run SampleApplicaiton.java with following params server server.yml from $MODULE_DIR$.  
1. What is $MODULE_DIR$ here? 
2. How to set params to SampleApplicaiton.java?

Thanks :)

**Comment by sergeytrasko** [comment]
Assuming you are trying to run it from IDE.

$MODULE_DIR$ is a variable used in IntelliJ IDEA to specify working directory for a module.

E.g. here is my configuration:
<img width="1072" alt="screen shot 2017-08-02 at 17 43 24" src="https://user-images.githubusercontent.com/8128865/28879181-2ad83b16-77aa-11e7-89db-4de963a18e5a.png">

If you are using Eclipse or any other IDE it should be somehow similar.

**Comment by arkadiyala** [comment]
Yes, I'm using Eclipse. 
Could you please help me on running this framework with eclipse. 
Thanks:)

**Comment by sergeytrasko** [comment]
In eclipse it's pretty much the same. I've created Run Configuration for 'Java Application' type:
<img width="800" alt="screen shot 2017-08-03 at 10 32 28" src="https://user-images.githubusercontent.com/8128865/28910889-310db82a-7837-11e7-85d3-2ad48ba62099.png">

And then provided 'Program arguments':
<img width="801" alt="screen shot 2017-08-03 at 10 33 52" src="https://user-images.githubusercontent.com/8128865/28910908-476fd5ee-7837-11e7-919d-7431a0db8c17.png">

All the rest parameters stayed as defaults.

Hope that helps.

**Comment by arkadiyala** [comment]
Right click on SampleApplicaiton.java--> Run as --> Run configurations --> Updated Project, Main Class and Program arguments per your screen shot and click on Run button. Then i see below error message.
Could you please help me on it.
 
Error: Could not find or load main class C:\workspace\Rest\cukes-rest-sample\src\main\java\lv\ctco\cukes\rest\SampleApplication.java

**Comment by arkadiyala** [comment]
Ran from RunCukesTest.java  and i got below result.  Thanks for your help
Tests run: 236, Failures: 0, Errors: 0, Skipped: 0

**Comment by arkadiyala** [comment]
Cucumber libraries are not downloaded into JRE System Library .  Please let me know what POM.xml has those Maven dependencies.  

Do I need to add Junit  Maven dependencies as well to run these scripts?

Thanks :)

**Comment by arkadiyala** [comment]
Is it running from your end with Eclipse? 
Could you please help me.

Thanks :)
