### ISSUE TITLE
Could not resolve dependencies for project lv.ctco.cukes:cukes-rest-sample:jar:0.0.5-SNAPSHOT

### ISSUE THREAD

**Issue by arkadiyala** [ctco/cukes#88]
Go to cukes-rest-sample->pom.xml -> Right click ->select 'run as' ->Click on Maven install then i see below error . Could you please help on it.

SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Cukes REST Sample Project 0.0.5-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for lv.ctco.cukes:cukes-rest-loadrunner:jar:0.0.5-SNAPSHOT is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.937s
[INFO] Finished at: Wed Aug 02 10:09:50 CDT 2017
[INFO] Final Memory: 6M/150M
[INFO] ------------------------------------------------------------------------
**_## [ERROR] Failed to execute goal on project cukes-rest-sample: Could not resolve dependencies for project lv.ctco.cukes:cukes-rest-sample:jar:0.0.5-SNAPSHOT: Could not find artifact lv.ctco.cukes:cukes-rest-loadrunner:jar:0.0.5-SNAPSHOT -> [Help 1]_**
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.

**Comment by sergeytrasko** [comment]
Cukes is organized as multi-module Maven project.
cukes-rest-sample depends on sibling module cukes-rest.
So you need to build/install the whole project (i.e. run your command on root pom.xml file), not a particular module.

**Comment by arkadiyala** [comment]
Thanks for your help. This issue has been resolved.

**Comment by arkadiyala** [comment]
Please let me know how to get extended report as below. 
https://github.com/intuit/karate/tree/master/karate-demo


Can i do below with this framework
a)Insert data into DB --> Then post web-service call --> Get Web-service response --> Compare Web-service response with DB values?

b)Get data(Example: name) from DB with SQL query(Example: Select id from table- name where id =1)--> Then post web-service call with name(Like https://myorg.com/name) --> Get Web-service response --> Compare Web-service response with entire DB values?

**Comment by sergeytrasko** [comment]
You need to write custom steps for working with database. Maybe it's a good candidate for cukes framework as well (pull requests are welcomed).

PS: also it's better to open separate issue with different question/clarification instead of commenting a closed one.
