### ISSUE TITLE
[Question] Calling/Executing Java Code within a feature file

### ISSUE THREAD

**Issue by ssadhoo** [ctco/cukes#91]
Is it possible to call some Java code from within a feature file. I want to perform some pre processing before I execute the test. Wanted to know if some one has tried it or there is a way to do some preprocessing ?

**Comment by sergeytrasko** [comment]
By default there is no such capability directly (i.e. have a predefined step that would allow to run any Java code). But you have 2 options here - choose one that fits your use case better

Option 1 - create your own step definitions that you can use inside your features

Option 2 - use plugins. Suits if you need to do some cross-cutting things applicable to all tests (e.g. logging, performance benchmarks, etc).

E.g.:
```java
package com.company.cukes;

import lv.ctco.cukes.core.extension.CukesPlugin;
....

public class MySuperPlugin implements CukesPlugin {
....
}
```
And the add it to `cukes.properties`:
```
# You can also specify multiple plugins separated with comma
cukes.plugins: com.company.cukes.MySuperPlugin 
```
